---
abstract: 'Log messages via Twitter'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Twitter
no_index:
  directory:
    - inc
    - t
requires:
  Log::Dispatch: 2.22
  Net::Twitter: 1.17
  perl: 5.8.1
resources:
  homepage: http://github.com/sartak/Log-Dispatch-Twitter/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Log-Dispatch-Twitter.git
version: 0.03
